#############
## Iosevka ##
#############

[buildPlans.Iosevka]
family = "Iosevka"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

    [buildPlans.Iosevka.ligations]
    inherits = "dlig"

[buildPlans.Iosevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Iosevka.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Iosevka.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.Iosevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Iosevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

##################
## Iosevka Slab ## 
##################

[buildPlans.IosevkaSlab]
family = "Iosevka Slab"
spacing = "normal"
serifs = "slab"
noCvSs = true
exportGlyphNames = false

    [buildPlans.IosevkaSlab.ligations]
    inherits = "dlig"

[buildPlans.IosevkaSlab.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaSlab.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaSlab.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaSlab.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaSlab.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

######################
## Iosevka Terminal ##
######################

[buildPlans.IosevkaTerminal]
family = "Iosevka Terminal"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

    [buildPlans.IosevkaTerminal.ligations]
    inherits = "dlig"

[buildPlans.IosevkaTerminal.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaTerminal.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaTerminal.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaTerminal.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaTerminal.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

###########################
## Iosevka Terminal Slab ##
###########################

[buildPlans.IosevkaTerminalSlab]
family = "Iosevka Terminal Slab"
spacing = "term"
serifs = "slab"
noCvSs = true
exportGlyphNames = false

    [buildPlans.IosevkaTerminalSlab.ligations]
    inherits = "dlig"

[buildPlans.IosevkaTerminalSlab.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaTerminalSlab.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaTerminalSlab.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaTerminalSlab.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaTerminalSlab.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

###################
## Iosevka Fixed ##
###################

[buildPlans.IosevkaFixed]
family = "Iosevka Fixed"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

    [buildPlans.IosevkaFixed.ligations]
    inherits = "dlig"

[buildPlans.IosevkaFixed.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaFixed.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaFixed.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaFixed.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaFixed.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

########################
## Iosevka Fixed Slab ##
########################

[buildPlans.IosevkaFixedSlab]
family = "Iosevka Fixed Slab"
spacing = "fixed"
serifs = "slab"
noCvSs = true
exportGlyphNames = false

    [buildPlans.IosevkaFixedSlab.ligations]
    inherits = "dlig"

[buildPlans.IosevkaFixedSlab.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaFixedSlab.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaFixedSlab.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaFixedSlab.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaFixedSlab.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

##################
## Iosevka Aile ##
##################

[buildPlans.IosevkaAile]
family = "Iosevka Aile"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

    [buildPlans.IosevkaAile.ligations]
    inherits = "dlig"

[buildPlans.IosevkaAile.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaAile.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaAile.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaAile.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaAile.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

####################
## Iosevka Etoile ##
####################

[buildPlans.IosevkaEtoile]
family = "Iosevka Etoile"
spacing = "quasi-proportional"
serifs = "slab"
noCvSs = true
exportGlyphNames = false

    [buildPlans.IosevkaEtoile.ligations]
    inherits = "dlig"

[buildPlans.IosevkaEtoile.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaEtoile.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaEtoile.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaEtoile.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaEtoile.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"