####################
## Iosevka Custom ##
####################

[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
lineHeight = 1.2

    [buildPlans.IosevkaCustom.ligations]
    inherits = "dlig"

[buildPlans.IosevkaCustom.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustom.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCustom.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaCustom.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCustom.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

#########################
## Iosevka Custom Slab ##
#########################

[buildPlans.IosevkaCustomSlab]
family = "Iosevka Custom Slab"
spacing = "normal"
serifs = "slab"
noCvSs = true
exportGlyphNames = false
lineHeight = 1.2

    [buildPlans.IosevkaCustomSlab.ligations]
    inherits = "dlig"

[buildPlans.IosevkaCustomSlab.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustomSlab.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCustomSlab.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaCustomSlab.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCustomSlab.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

##########################
## Iosevka Custom Curly ##
##########################

[buildPlans.IosevkaCustomCurly]
family = "Iosevka Custom Curly"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
lineHeight = 1.2

    [buildPlans.IosevkaCustomCurly.variants]
    inherits = "ss20"

    [buildPlans.IosevkaCustomCurly.ligations]
    inherits = "dlig"

[buildPlans.IosevkaCustomCurly.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustomCurly.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCustomCurly.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaCustomCurly.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCustomCurly.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

###############################
## Iosevka Custom Curly Slab ##
###############################

[buildPlans.IosevkaCustomCurlySlab]
family = "Iosevka Custom Curly Slab"
spacing = "normal"
serifs = "slab"
noCvSs = true
exportGlyphNames = false
lineHeight = 1.2

    [buildPlans.IosevkaCustomCurlySlab.variants]
    inherits = "ss20"

    [buildPlans.IosevkaCustomCurlySlab.ligations]
    inherits = "dlig"

[buildPlans.IosevkaCustomCurlySlab.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustomCurlySlab.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCustomCurlySlab.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaCustomCurlySlab.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCustomCurlySlab.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

#############################
## Iosevka Custom Terminal ##
#############################

[buildPlans.IosevkaCustomTerminal]
family = "Iosevka Custom Terminal"
spacing = "normal"
serifs = "term"
noCvSs = true
exportGlyphNames = false
lineHeight = 1.2

    [buildPlans.IosevkaCustomTerminal.ligations]
    inherits = "dlig"

[buildPlans.IosevkaCustomTerminal.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustomTerminal.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCustomTerminal.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaCustomTerminal.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCustomTerminal.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

##################################
## Iosevka Custom Terminal Slab ##
##################################

[buildPlans.IosevkaCustomTerminalSlab]
family = "Iosevka Custom Terminal Slab"
spacing = "term"
serifs = "slab"
noCvSs = true
exportGlyphNames = false
lineHeight = 1.2

    [buildPlans.IosevkaCustomTerminalSlab.ligations]
    inherits = "dlig"

[buildPlans.IosevkaCustomTerminalSlab.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustomTerminalSlab.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCustomTerminalSlab.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaCustomTerminalSlab.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCustomTerminalSlab.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

##########################
## Iosevka Custom Fixed ##
##########################

[buildPlans.IosevkaCustomFixed]
family = "Iosevka Custom Fixed"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
lineHeight = 1.2

    [buildPlans.IosevkaCustomFixed.ligations]
    inherits = "dlig"

[buildPlans.IosevkaCustomFixed.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustomFixed.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCustomFixed.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaCustomFixed.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCustomFixed.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

###############################
## Iosevka Custom Fixed Slab ##
###############################

[buildPlans.IosevkaCustomFixedSlab]
family = "Iosevka Custom Fixed Slab"
spacing = "fixed"
serifs = "slab"
noCvSs = true
exportGlyphNames = false
lineHeight = 1.2

    [buildPlans.IosevkaCustomFixedSlab.ligations]
    inherits = "dlig"

[buildPlans.IosevkaCustomFixedSlab.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustomFixedSlab.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCustomFixedSlab.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaCustomFixedSlab.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCustomFixedSlab.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

#########################
## Iosevka Custom Aile ##
#########################

[buildPlans.IosevkaCustomAile]
family = "Iosevka Custom Aile"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
lineHeight = 1.2

    [buildPlans.IosevkaCustomAile.ligations]
    inherits = "dlig"

[buildPlans.IosevkaCustomAile.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustomAile.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCustomAile.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaCustomAile.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCustomAile.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

###########################
## Iosevka Custom Etoile ##
###########################

[buildPlans.IosevkaCustomEtoile]
family = "Iosevka Custom Etoile"
spacing = "quasi-proportional"
serifs = "slab"
noCvSs = true
exportGlyphNames = false
lineHeight = 1.2

    [buildPlans.IosevkaCustomEtoile.ligations]
    inherits = "dlig"

[buildPlans.IosevkaCustomEtoile.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustomEtoile.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCustomEtoile.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaCustomEtoile.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCustomEtoile.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
