# ~/.config/starship.toml
# https://starship.rs/config/

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = '$shell $directory$character'

right_format = '$git_branch$git_status'

[directory]
truncation_length = 3
truncation_symbol = '...'
home_symbol = ''
read_only = " "

[line_break]
disabled = true

[shell]
zsh_indicator = 'zsh'
fish_indicator = 'fish'
style = 'yellow bold'
format = '[ $indicator]($style)'
disabled = false

[git_branch]
symbol = ' '
style = 'bold purple'
format = '[$symbol$branch]($style) '

[git_status]
style = 'red bold'
format = '[$all_status$ahead_behind]($style)'
disabled = false